-- VHDL Entity zybo_aes_hdl_lib.aes_ctr_controller.symbol
--
-- Created:
--          by - Shahin.UNKNOWN (DESKTOP-THSND8B)
--          at - 11:12:52 06/16/2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY aes_ctr_controller IS
   PORT( 
      aes_busy                 : IN     std_logic;
      aes_ctr_start            : IN     std_logic;
      aes_done                 : IN     std_logic;
      clk                      : IN     std_logic;
      collector_busy           : IN     std_logic;
      collector_done           : IN     std_logic;
      reset_n                  : IN     std_logic;
      serializer_busy          : IN     std_logic;
      serializer_done          : IN     std_logic;
      serializer_last_done     : IN     std_logic;
      aes_ctr_idle             : OUT    std_logic;
      initialize_counter_block : OUT    std_logic;
      produce_counter_block    : OUT    std_logic;
      start_aes                : OUT    std_logic;
      start_collector          : OUT    std_logic;
      start_serializer         : OUT    std_logic
   );

-- Declarations

END aes_ctr_controller ;

--
-- VHDL Architecture zybo_aes_hdl_lib.aes_ctr_controller.struct
--
-- Created:
--          by - Shahin.UNKNOWN (DESKTOP-THSND8B)
--          at - 11:12:52 06/16/2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF aes_ctr_controller IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL aes_ctr_busy           : std_logic;
   SIGNAL aes_not_ready          : std_logic;
   SIGNAL aes_not_started        : std_logic;
   SIGNAL aes_ready              : std_logic;
   SIGNAL aes_started            : std_logic;
   SIGNAL block_busy             : std_logic;
   SIGNAL block_idle             : std_logic;
   SIGNAL collector_not_ready    : std_logic;
   SIGNAL collector_not_started  : std_logic;
   SIGNAL collector_ready        : std_logic;
   SIGNAL collector_started      : std_logic;
   SIGNAL din0                   : std_logic;
   SIGNAL dout                   : std_logic;
   SIGNAL dout1                  : std_logic;
   SIGNAL dout10                 : std_logic;
   SIGNAL dout11                 : std_logic;
   SIGNAL dout12                 : std_logic;
   SIGNAL dout13                 : std_logic;
   SIGNAL dout14                 : std_logic;
   SIGNAL dout15                 : std_logic;
   SIGNAL dout16                 : std_logic;
   SIGNAL dout17                 : std_logic;
   SIGNAL dout18                 : std_logic;
   SIGNAL dout2                  : std_logic;
   SIGNAL dout20                 : std_logic;
   SIGNAL dout21                 : std_logic;
   SIGNAL dout22                 : std_logic;
   SIGNAL dout3                  : std_logic;
   SIGNAL dout4                  : std_logic;
   SIGNAL dout5                  : std_logic;
   SIGNAL dout6                  : std_logic;
   SIGNAL dout7                  : std_logic;
   SIGNAL dout8                  : std_logic;
   SIGNAL dout9                  : std_logic;
   SIGNAL serializer_not_started : std_logic;
   SIGNAL serializer_started     : std_logic;

   -- Implicit buffer signal declarations
   SIGNAL aes_ctr_idle_internal             : std_logic;
   SIGNAL initialize_counter_block_internal : std_logic;
   SIGNAL produce_counter_block_internal    : std_logic;
   SIGNAL start_aes_internal                : std_logic;
   SIGNAL start_collector_internal          : std_logic;
   SIGNAL start_serializer_internal         : std_logic;


   -- ModuleWare signal declarations(v1.12) for instance 'U_15' of 'adff'
   SIGNAL mw_U_15reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.12) for instance 'U_16' of 'adff'
   SIGNAL mw_U_16reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.12) for instance 'U_18' of 'adff'
   SIGNAL mw_U_18reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.12) for instance 'U_19' of 'adff'
   SIGNAL mw_U_19reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.12) for instance 'U_28' of 'adff'
   SIGNAL mw_U_28reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.12) for instance 'U_35' of 'adff'
   SIGNAL mw_U_35reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.12) for instance 'U_41' of 'adff'
   SIGNAL mw_U_41reg_cval : std_logic;


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_15' of 'adff'
   aes_ctr_busy <= mw_U_15reg_cval;
   u_15seq_proc: PROCESS (clk)BEGIN
      IF (clk'EVENT AND clk='1') THEN
         IF (reset_n = '0') THEN
            mw_U_15reg_cval <= '0';
         ELSIF (dout2 = '1') THEN
            mw_U_15reg_cval <= aes_ctr_idle_internal;
         END IF;
      END IF;
   END PROCESS u_15seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_16' of 'adff'
   block_busy <= mw_U_16reg_cval;
   u_16seq_proc: PROCESS (clk)BEGIN
      IF (clk'EVENT AND clk='1') THEN
         IF (reset_n = '0') THEN
            mw_U_16reg_cval <= '0';
         ELSIF (dout5 = '1') THEN
            mw_U_16reg_cval <= block_idle;
         END IF;
      END IF;
   END PROCESS u_16seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_18' of 'adff'
   aes_started <= mw_U_18reg_cval;
   u_18seq_proc: PROCESS (clk)BEGIN
      IF (clk'EVENT AND clk='1') THEN
         IF (reset_n = '0') THEN
            mw_U_18reg_cval <= '0';
         ELSIF (dout7 = '1') THEN
            mw_U_18reg_cval <= aes_not_started;
         END IF;
      END IF;
   END PROCESS u_18seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_19' of 'adff'
   collector_started <= mw_U_19reg_cval;
   u_19seq_proc: PROCESS (clk)BEGIN
      IF (clk'EVENT AND clk='1') THEN
         IF (reset_n = '0') THEN
            mw_U_19reg_cval <= '0';
         ELSIF (dout9 = '1') THEN
            mw_U_19reg_cval <= collector_not_started;
         END IF;
      END IF;
   END PROCESS u_19seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_28' of 'adff'
   serializer_started <= mw_U_28reg_cval;
   u_28seq_proc: PROCESS (clk)BEGIN
      IF (clk'EVENT AND clk='1') THEN
         IF (reset_n = '0') THEN
            mw_U_28reg_cval <= '0';
         ELSIF (dout12 = '1') THEN
            mw_U_28reg_cval <= serializer_not_started;
         END IF;
      END IF;
   END PROCESS u_28seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_35' of 'adff'
   aes_ready <= mw_U_35reg_cval;
   u_35seq_proc: PROCESS (clk)BEGIN
      IF (clk'EVENT AND clk='1') THEN
         IF (reset_n = '0') THEN
            mw_U_35reg_cval <= '0';
         ELSIF (dout17 = '1') THEN
            mw_U_35reg_cval <= aes_not_ready;
         END IF;
      END IF;
   END PROCESS u_35seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_41' of 'adff'
   collector_ready <= mw_U_41reg_cval;
   u_41seq_proc: PROCESS (clk)BEGIN
      IF (clk'EVENT AND clk='1') THEN
         IF (reset_n = '0') THEN
            mw_U_41reg_cval <= '0';
         ELSIF (dout22 = '1') THEN
            mw_U_41reg_cval <= collector_not_ready;
         END IF;
      END IF;
   END PROCESS u_41seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_0' of 'and'
   initialize_counter_block_internal <= aes_ctr_idle_internal
                                        AND aes_ctr_start;

   -- ModuleWare code(v1.12) for instance 'U_3' of 'and'
   dout3 <= aes_ctr_busy AND serializer_last_done;

   -- ModuleWare code(v1.12) for instance 'U_6' of 'and'
   dout <= aes_ctr_busy AND block_idle;

   -- ModuleWare code(v1.12) for instance 'U_8' of 'and'
   dout6 <= block_busy AND serializer_done;

   -- ModuleWare code(v1.12) for instance 'U_10' of 'and'
   start_aes_internal <= aes_not_started AND block_busy;

   -- ModuleWare code(v1.12) for instance 'U_12' of 'and'
   din0 <= start_aes_internal AND aes_busy;

   -- ModuleWare code(v1.12) for instance 'U_14' of 'and'
   dout8 <= block_idle AND aes_started;

   -- ModuleWare code(v1.12) for instance 'U_17' of 'and'
   start_collector_internal <= collector_not_started AND block_busy;

   -- ModuleWare code(v1.12) for instance 'U_20' of 'and'
   start_serializer_internal <= serializer_not_started AND dout15;

   -- ModuleWare code(v1.12) for instance 'U_21' of 'and'
   dout10 <= start_collector_internal AND collector_busy;

   -- ModuleWare code(v1.12) for instance 'U_22' of 'and'
   dout11 <= block_idle AND collector_started;

   -- ModuleWare code(v1.12) for instance 'U_25' of 'and'
   dout13 <= start_serializer_internal AND serializer_busy;

   -- ModuleWare code(v1.12) for instance 'U_26' of 'and'
   dout14 <= block_idle AND serializer_started;

   -- ModuleWare code(v1.12) for instance 'U_30' of 'and'
   dout15 <= aes_ready AND collector_ready;

   -- ModuleWare code(v1.12) for instance 'U_31' of 'and'
   dout1 <= aes_not_ready AND block_busy;

   -- ModuleWare code(v1.12) for instance 'U_32' of 'and'
   dout16 <= dout1 AND aes_done;

   -- ModuleWare code(v1.12) for instance 'U_33' of 'and'
   dout4 <= block_idle AND aes_ready;

   -- ModuleWare code(v1.12) for instance 'U_37' of 'and'
   dout18 <= collector_not_ready AND block_busy;

   -- ModuleWare code(v1.12) for instance 'U_38' of 'and'
   dout21 <= block_idle AND collector_ready;

   -- ModuleWare code(v1.12) for instance 'U_39' of 'and'
   dout20 <= dout18 AND collector_done;

   -- ModuleWare code(v1.12) for instance 'U_5' of 'inv'
   aes_ctr_idle_internal <= NOT(aes_ctr_busy);

   -- ModuleWare code(v1.12) for instance 'U_7' of 'inv'
   block_idle <= NOT(block_busy);

   -- ModuleWare code(v1.12) for instance 'U_11' of 'inv'
   aes_not_started <= NOT(aes_started);

   -- ModuleWare code(v1.12) for instance 'U_24' of 'inv'
   collector_not_started <= NOT(collector_started);

   -- ModuleWare code(v1.12) for instance 'U_29' of 'inv'
   serializer_not_started <= NOT(serializer_started);

   -- ModuleWare code(v1.12) for instance 'U_36' of 'inv'
   aes_not_ready <= NOT(aes_ready);

   -- ModuleWare code(v1.12) for instance 'U_42' of 'inv'
   collector_not_ready <= NOT(collector_ready);

   -- ModuleWare code(v1.12) for instance 'U_2' of 'or'
   dout2 <= initialize_counter_block_internal OR dout3;

   -- ModuleWare code(v1.12) for instance 'U_4' of 'or'
   produce_counter_block_internal <= initialize_counter_block_internal
                                     OR dout;

   -- ModuleWare code(v1.12) for instance 'U_9' of 'or'
   dout5 <= produce_counter_block_internal OR dout6;

   -- ModuleWare code(v1.12) for instance 'U_13' of 'or'
   dout7 <= din0 OR dout8;

   -- ModuleWare code(v1.12) for instance 'U_23' of 'or'
   dout9 <= dout10 OR dout11;

   -- ModuleWare code(v1.12) for instance 'U_27' of 'or'
   dout12 <= dout13 OR dout14;

   -- ModuleWare code(v1.12) for instance 'U_34' of 'or'
   dout17 <= dout16 OR dout4;

   -- ModuleWare code(v1.12) for instance 'U_40' of 'or'
   dout22 <= dout20 OR dout21;

   -- Instance port mappings.

   -- Implicit buffered output assignments
   aes_ctr_idle             <= aes_ctr_idle_internal;
   initialize_counter_block <= initialize_counter_block_internal;
   produce_counter_block    <= produce_counter_block_internal;
   start_aes                <= start_aes_internal;
   start_collector          <= start_collector_internal;
   start_serializer         <= start_serializer_internal;

END struct;
