-- VHDL Entity zybo_aes_hdl_lib.aes_encrypt_128.symbol
--
-- Created:
--          by - Shahin.UNKNOWN (DESKTOP-THSND8B)
--          at - 11:37:02 06/15/2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY aes_encrypt_128 IS
   PORT( 
      aes_data_in  : IN     std_logic_vector (127 DOWNTO 0);
      aes_key_in   : IN     std_logic_vector (127 DOWNTO 0);
      aes_start    : IN     std_logic;
      clk          : IN     std_logic;
      reset_n      : IN     std_logic;
      aes_busy     : OUT    std_logic;
      aes_data_out : OUT    std_logic_vector (127 DOWNTO 0);
      aes_done     : OUT    std_logic
   );

-- Declarations

END aes_encrypt_128 ;

--
-- VHDL Architecture zybo_aes_hdl_lib.aes_encrypt_128.struct
--
-- Created:
--          by - Shahin.UNKNOWN (DESKTOP-THSND8B)
--          at - 11:37:02 06/15/2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY zybo_aes_hdl_lib;

ARCHITECTURE struct OF aes_encrypt_128 IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL all_one              : std_logic_vector(3 DOWNTO 0);
   SIGNAL columns_mixed        : std_logic_vector(127 DOWNTO 0);
   SIGNAL constant_ten         : std_logic_vector(3 DOWNTO 0);
   SIGNAL d                    : std_logic_vector(3 DOWNTO 0);
   SIGNAL data_next            : std_logic_vector(127 DOWNTO 0);
   SIGNAL din0                 : std_logic_vector(127 DOWNTO 0);
   SIGNAL din2                 : std_logic_vector(3 DOWNTO 0);
   SIGNAL dout1                : std_logic_vector(127 DOWNTO 0);
   SIGNAL dout2                : std_logic_vector(127 DOWNTO 0);
   SIGNAL dout3                : std_logic_vector(3 DOWNTO 0);
   SIGNAL equal_to_ten         : std_logic;
   SIGNAL key_expand_next      : std_logic_vector(127 DOWNTO 0);
   SIGNAL key_expand_round_in  : std_logic_vector(127 DOWNTO 0);
   SIGNAL key_expand_round_out : std_logic_vector(127 DOWNTO 0);
   SIGNAL load                 : std_logic;
   SIGNAL round_index          : std_logic_vector(3 DOWNTO 0);
   SIGNAL shift_rows_data_in   : std_logic_vector(127 DOWNTO 0);
   SIGNAL shift_rows_out       : std_logic_vector(127 DOWNTO 0);
   SIGNAL sub_bytes_in         : std_logic_vector(127 DOWNTO 0);

   -- Implicit buffer signal declarations
   SIGNAL aes_busy_internal : std_logic;


   -- ModuleWare signal declarations(v1.12) for instance 'U_4' of 'adff'
   SIGNAL mw_U_4reg_cval : std_logic_vector(127 DOWNTO 0);

   -- ModuleWare signal declarations(v1.12) for instance 'U_5' of 'adff'
   SIGNAL mw_U_5reg_cval : std_logic_vector(127 DOWNTO 0);

   -- ModuleWare signal declarations(v1.12) for instance 'U_6' of 'adff'
   SIGNAL mw_U_6reg_cval : std_logic_vector(3 DOWNTO 0);

   -- ModuleWare signal declarations(v1.12) for instance 'U_14' of 'adff'
   SIGNAL mw_U_14reg_cval : std_logic_vector(127 DOWNTO 0);

   -- ModuleWare signal declarations(v1.12) for instance 'U_15' of 'adff'
   SIGNAL mw_U_15reg_cval : std_logic;

   -- Component Declarations
   COMPONENT aes_key_expand_round
   PORT (
      key_expand_round_in  : IN     std_logic_vector (127 DOWNTO 0);
      round_index          : IN     std_logic_vector (3 DOWNTO 0);
      key_expand_round_out : OUT    std_logic_vector (127 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT aes_mix_columns
   PORT (
      columns_in    : IN     std_logic_vector (127 DOWNTO 0);
      columns_mixed : OUT    std_logic_vector (127 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT aes_shift_rows
   PORT (
      shift_rows_in  : IN     std_logic_vector (127 DOWNTO 0);
      shift_rows_out : OUT    std_logic_vector (127 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT aes_sub_bytes
   PORT (
      sub_bytes_in  : IN     std_logic_vector (127 DOWNTO 0);
      sub_bytes_out : OUT    std_logic_vector (127 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : aes_key_expand_round USE ENTITY zybo_aes_hdl_lib.aes_key_expand_round;
   FOR ALL : aes_mix_columns USE ENTITY zybo_aes_hdl_lib.aes_mix_columns;
   FOR ALL : aes_shift_rows USE ENTITY zybo_aes_hdl_lib.aes_shift_rows;
   FOR ALL : aes_sub_bytes USE ENTITY zybo_aes_hdl_lib.aes_sub_bytes;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_4' of 'adff'
   sub_bytes_in <= mw_U_4reg_cval;
   u_4seq_proc: PROCESS (clk)BEGIN
      IF (clk'EVENT AND clk='1') THEN
         IF (reset_n = '0') THEN
            mw_U_4reg_cval <= x"00000000000000000000000000000000";
         ELSIF (load = '1') THEN
            mw_U_4reg_cval <= data_next;
         END IF;
      END IF;
   END PROCESS u_4seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_5' of 'adff'
   key_expand_round_in <= mw_U_5reg_cval;
   u_5seq_proc: PROCESS (clk)BEGIN
      IF (clk'EVENT AND clk='1') THEN
         IF (reset_n = '0') THEN
            mw_U_5reg_cval <= x"00000000000000000000000000000000";
         ELSIF (load = '1') THEN
            mw_U_5reg_cval <= key_expand_next;
         END IF;
      END IF;
   END PROCESS u_5seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_6' of 'adff'
   round_index <= mw_U_6reg_cval;
   u_6seq_proc: PROCESS (clk)BEGIN
      IF (clk'EVENT AND clk='1') THEN
         IF (reset_n = '0') THEN
            mw_U_6reg_cval <= "0000";
         ELSIF (load = '1') THEN
            mw_U_6reg_cval <= d;
         END IF;
      END IF;
   END PROCESS u_6seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_14' of 'adff'
   aes_data_out <= mw_U_14reg_cval;
   u_14seq_proc: PROCESS (clk)BEGIN
      IF (clk'EVENT AND clk='1') THEN
         IF (reset_n = '0') THEN
            mw_U_14reg_cval <= x"00000000000000000000000000000000";
         ELSIF (equal_to_ten = '1') THEN
            mw_U_14reg_cval <= dout2;
         END IF;
      END IF;
   END PROCESS u_14seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_15' of 'adff'
   aes_done <= mw_U_15reg_cval;
   u_15seq_proc: PROCESS (clk)BEGIN
      IF (clk'EVENT AND clk='1') THEN
         IF (reset_n = '0') THEN
            mw_U_15reg_cval <= '0';
         ELSE
            mw_U_15reg_cval <= equal_to_ten;
         END IF;
      END IF;
   END PROCESS u_15seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_19' of 'constval'
   constant_ten <= "1010";

   -- ModuleWare code(v1.12) for instance 'U_23' of 'constval'
   din2 <= "0000";

   -- ModuleWare code(v1.12) for instance 'U_7' of 'inc'
   u_7combo_proc: PROCESS (round_index)
   VARIABLE temp_din : std_logic_vector(4 DOWNTO 0);
   VARIABLE temp_sum : unsigned(4 DOWNTO 0);
   BEGIN
      temp_din := '0' & round_index;
      temp_sum := (unsigned(temp_din) + '1');
      dout3 <= conv_std_logic_vector(temp_sum(3 DOWNTO 0),4);
   END PROCESS u_7combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_10' of 'mux'
   u_10combo_proc: PROCESS(aes_key_in, key_expand_round_out, 
                           aes_busy_internal)
   BEGIN
      CASE aes_busy_internal IS
      WHEN '0' => key_expand_next <= aes_key_in;
      WHEN '1' => key_expand_next <= key_expand_round_out;
      WHEN OTHERS => key_expand_next <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_10combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_11' of 'mux'
   u_11combo_proc: PROCESS(din0, dout1, aes_busy_internal)
   BEGIN
      CASE aes_busy_internal IS
      WHEN '0' => data_next <= din0;
      WHEN '1' => data_next <= dout1;
      WHEN OTHERS => data_next <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_11combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_16' of 'mux'
   u_16combo_proc: PROCESS(dout3, din2, equal_to_ten)
   BEGIN
      CASE equal_to_ten IS
      WHEN '0' => d <= dout3;
      WHEN '1' => d <= din2;
      WHEN OTHERS => d <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_16combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_24' of 'or'
   load <= aes_start OR aes_busy_internal;

   -- ModuleWare code(v1.12) for instance 'U_20' of 'tand'
   equal_to_ten <= all_one(0) AND all_one(1) AND all_one(2)
                   AND all_one(3);

   -- ModuleWare code(v1.12) for instance 'U_17' of 'tor'
   aes_busy_internal <= round_index(0) OR round_index(1) OR round_index(2)
                        OR round_index(3);

   -- ModuleWare code(v1.12) for instance 'U_18' of 'xnor'
   all_one <= NOT(round_index XOR constant_ten);

   -- ModuleWare code(v1.12) for instance 'U_8' of 'xor'
   din0 <= aes_data_in XOR aes_key_in;

   -- ModuleWare code(v1.12) for instance 'U_12' of 'xor'
   dout2 <= shift_rows_out XOR key_expand_round_out;

   -- ModuleWare code(v1.12) for instance 'U_21' of 'xor'
   dout1 <= columns_mixed XOR key_expand_round_out;

   -- Instance port mappings.
   U_0 : aes_key_expand_round
      PORT MAP (
         key_expand_round_in  => key_expand_round_in,
         round_index          => round_index,
         key_expand_round_out => key_expand_round_out
      );
   U_2 : aes_mix_columns
      PORT MAP (
         columns_in    => shift_rows_out,
         columns_mixed => columns_mixed
      );
   U_1 : aes_shift_rows
      PORT MAP (
         shift_rows_in  => shift_rows_data_in,
         shift_rows_out => shift_rows_out
      );
   U_3 : aes_sub_bytes
      PORT MAP (
         sub_bytes_in  => sub_bytes_in,
         sub_bytes_out => shift_rows_data_in
      );

   -- Implicit buffered output assignments
   aes_busy <= aes_busy_internal;

END struct;
