-- VHDL Entity zybo_aes_hdl_lib.aes_ctr_output_serializer.symbol
--
-- Created:
--          by - Shahin.UNKNOWN (DESKTOP-THSND8B)
--          at - 14:51:34 06/15/2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY aes_ctr_output_serializer IS
   PORT( 
      ciphertext_block_in  : IN     std_logic_vector (127 DOWNTO 0);
      clk                  : IN     std_logic;
      keep_block_in        : IN     std_logic_vector (15 DOWNTO 0);
      last_word_mask_in    : IN     std_logic_vector (3 DOWNTO 0);
      m_axis_tready        : IN     std_logic;
      reset_n              : IN     std_logic;
      start_serializer     : IN     std_logic;
      m_axis_tdata         : OUT    std_logic_vector (31 DOWNTO 0);
      m_axis_tkeep         : OUT    std_logic_vector (3 DOWNTO 0);
      m_axis_tlast         : OUT    std_logic;
      m_axis_tvalid        : OUT    std_logic;
      serializer_busy      : OUT    std_logic;
      serializer_done      : OUT    std_logic;
      serializer_last_done : OUT    std_logic
   );

-- Declarations

END aes_ctr_output_serializer ;

--
-- VHDL Architecture zybo_aes_hdl_lib.aes_ctr_output_serializer.struct
--
-- Created:
--          by - Shahin.UNKNOWN (DESKTOP-THSND8B)
--          at - 14:51:34 06/15/2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY zybo_aes_hdl_lib;

ARCHITECTURE struct OF aes_ctr_output_serializer IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL clear          : std_logic;
   SIGNAL dout           : std_logic_vector(3 DOWNTO 0);
   SIGNAL dout0          : std_logic_vector(31 DOWNTO 0);
   SIGNAL dout1          : std_logic_vector(31 DOWNTO 0);
   SIGNAL dout10         : std_logic;
   SIGNAL dout11         : std_logic;
   SIGNAL dout12         : std_logic;
   SIGNAL dout13         : std_logic;
   SIGNAL dout14         : std_logic;
   SIGNAL dout15         : std_logic;
   SIGNAL dout16         : std_logic;
   SIGNAL dout2          : std_logic_vector(31 DOWNTO 0);
   SIGNAL dout3          : std_logic_vector(31 DOWNTO 0);
   SIGNAL dout4          : std_logic_vector(3 DOWNTO 0);
   SIGNAL dout5          : std_logic_vector(3 DOWNTO 0);
   SIGNAL dout6          : std_logic_vector(3 DOWNTO 0);
   SIGNAL dout7          : std_logic_vector(3 DOWNTO 0);
   SIGNAL dout8          : std_logic;
   SIGNAL dout9          : std_logic;
   SIGNAL q              : std_logic_vector(127 DOWNTO 0);
   SIGNAL q1             : std_logic_vector(15 DOWNTO 0);
   SIGNAL q2             : std_logic_vector(3 DOWNTO 0);
   SIGNAL state_is_idle  : std_logic;
   SIGNAL state_is_word1 : std_logic;
   SIGNAL state_is_word2 : std_logic;
   SIGNAL state_is_word3 : std_logic;
   SIGNAL state_is_word4 : std_logic;
   SIGNAL state_out      : std_logic_vector(2 DOWNTO 0);

   -- Implicit buffer signal declarations
   SIGNAL m_axis_tlast_internal    : std_logic;
   SIGNAL serializer_busy_internal : std_logic;


   -- ModuleWare signal declarations(v1.12) for instance 'U_6' of 'adff'
   SIGNAL mw_U_6reg_cval : std_logic_vector(127 DOWNTO 0);

   -- ModuleWare signal declarations(v1.12) for instance 'U_7' of 'adff'
   SIGNAL mw_U_7reg_cval : std_logic_vector(15 DOWNTO 0);

   -- ModuleWare signal declarations(v1.12) for instance 'U_11' of 'adff'
   SIGNAL mw_U_11reg_cval : std_logic_vector(3 DOWNTO 0);

   -- ModuleWare signal declarations(v1.12) for instance 'U_40' of 'adff'
   SIGNAL mw_U_40reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.12) for instance 'U_41' of 'adff'
   SIGNAL mw_U_41reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.12) for instance 'U_0' of 'split'
   SIGNAL mw_U_0temp_din : std_logic_vector(127 DOWNTO 0);

   -- ModuleWare signal declarations(v1.12) for instance 'U_1' of 'split'
   SIGNAL mw_U_1temp_din : std_logic_vector(15 DOWNTO 0);

   -- ModuleWare signal declarations(v1.12) for instance 'U_2' of 'split'
   SIGNAL mw_U_2temp_din : std_logic_vector(3 DOWNTO 0);

   -- Component Declarations
   COMPONENT aes_ctr_state_counter
   PORT (
      advance   : IN     std_logic ;
      clear     : IN     std_logic ;
      clk       : IN     std_logic ;
      reset_n   : IN     std_logic ;
      state_out : OUT    std_logic_vector (2 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT aes_ctr_state_decoder
   PORT (
      state_in       : IN     std_logic_vector (2 DOWNTO 0);
      state_is_busy  : OUT    std_logic ;
      state_is_idle  : OUT    std_logic ;
      state_is_word1 : OUT    std_logic ;
      state_is_word2 : OUT    std_logic ;
      state_is_word3 : OUT    std_logic ;
      state_is_word4 : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : aes_ctr_state_counter USE ENTITY zybo_aes_hdl_lib.aes_ctr_state_counter;
   FOR ALL : aes_ctr_state_decoder USE ENTITY zybo_aes_hdl_lib.aes_ctr_state_decoder;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_6' of 'adff'
   q <= mw_U_6reg_cval;
   u_6seq_proc: PROCESS (clk)BEGIN
      IF (clk'EVENT AND clk='1') THEN
         IF (reset_n = '0') THEN
            mw_U_6reg_cval <= x"00000000000000000000000000000000";
         ELSIF (dout12 = '1') THEN
            mw_U_6reg_cval <= ciphertext_block_in;
         END IF;
      END IF;
   END PROCESS u_6seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_7' of 'adff'
   q1 <= mw_U_7reg_cval;
   u_7seq_proc: PROCESS (clk)BEGIN
      IF (clk'EVENT AND clk='1') THEN
         IF (reset_n = '0') THEN
            mw_U_7reg_cval <= x"0000";
         ELSIF (dout12 = '1') THEN
            mw_U_7reg_cval <= keep_block_in;
         END IF;
      END IF;
   END PROCESS u_7seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_11' of 'adff'
   q2 <= mw_U_11reg_cval;
   u_11seq_proc: PROCESS (clk)BEGIN
      IF (clk'EVENT AND clk='1') THEN
         IF (reset_n = '0') THEN
            mw_U_11reg_cval <= "0000";
         ELSIF (dout12 = '1') THEN
            mw_U_11reg_cval <= last_word_mask_in;
         END IF;
      END IF;
   END PROCESS u_11seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_40' of 'adff'
   serializer_done <= mw_U_40reg_cval;
   u_40seq_proc: PROCESS (clk)BEGIN
      IF (clk'EVENT AND clk='1') THEN
         IF (reset_n = '0') THEN
            mw_U_40reg_cval <= '0';
         ELSE
            mw_U_40reg_cval <= clear;
         END IF;
      END IF;
   END PROCESS u_40seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_41' of 'adff'
   serializer_last_done <= mw_U_41reg_cval;
   u_41seq_proc: PROCESS (clk)BEGIN
      IF (clk'EVENT AND clk='1') THEN
         IF (reset_n = '0') THEN
            mw_U_41reg_cval <= '0';
         ELSE
            mw_U_41reg_cval <= dout16;
         END IF;
      END IF;
   END PROCESS u_41seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_12' of 'and'
   dout12 <= state_is_idle AND start_serializer;

   -- ModuleWare code(v1.12) for instance 'U_13' of 'and'
   dout13 <= serializer_busy_internal AND m_axis_tready;

   -- ModuleWare code(v1.12) for instance 'U_15' of 'and'
   dout15 <= state_is_word4 AND m_axis_tready;

   -- ModuleWare code(v1.12) for instance 'U_16' of 'and'
   dout16 <= m_axis_tlast_internal AND m_axis_tready;

   -- ModuleWare code(v1.12) for instance 'U_5' of 'merge'
   dout <= state_is_word1 & state_is_word2 & state_is_word3 & state_is_word4;

   -- ModuleWare code(v1.12) for instance 'U_8' of 'omux'
   u_8combo_proc: PROCESS(dout0, dout1, dout2, dout3, dout)
   BEGIN
      m_axis_tdata <= (OTHERS => '0');
      CASE dout IS
      WHEN "0001" => m_axis_tdata <= dout0;
      WHEN "0010" => m_axis_tdata <= dout1;
      WHEN "0100" => m_axis_tdata <= dout2;
      WHEN "1000" => m_axis_tdata <= dout3;
      WHEN OTHERS => m_axis_tdata <= (OTHERS => '0');
      END CASE;
   END PROCESS u_8combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_9' of 'omux'
   u_9combo_proc: PROCESS(dout4, dout5, dout6, dout7, dout)
   BEGIN
      m_axis_tkeep <= (OTHERS => '0');
      CASE dout IS
      WHEN "0001" => m_axis_tkeep <= dout4;
      WHEN "0010" => m_axis_tkeep <= dout5;
      WHEN "0100" => m_axis_tkeep <= dout6;
      WHEN "1000" => m_axis_tkeep <= dout7;
      WHEN OTHERS => m_axis_tkeep <= (OTHERS => '0');
      END CASE;
   END PROCESS u_9combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_10' of 'omux'
   u_10combo_proc: PROCESS(dout8, dout9, dout10, dout11, dout)
   BEGIN
      m_axis_tlast_internal <= '0';
      CASE dout IS
      WHEN "0001" => m_axis_tlast_internal <= dout8;
      WHEN "0010" => m_axis_tlast_internal <= dout9;
      WHEN "0100" => m_axis_tlast_internal <= dout10;
      WHEN "1000" => m_axis_tlast_internal <= dout11;
      WHEN OTHERS => m_axis_tlast_internal <= '0';
      END CASE;
   END PROCESS u_10combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_14' of 'or'
   dout14 <= dout12 OR dout13;

   -- ModuleWare code(v1.12) for instance 'U_17' of 'or'
   clear <= dout15 OR dout16;

   -- ModuleWare code(v1.12) for instance 'U_18' of 'or'
   m_axis_tvalid <= state_is_word1 OR state_is_word2 OR state_is_word3
                    OR state_is_word4;

   -- ModuleWare code(v1.12) for instance 'U_0' of 'split'
   mw_U_0temp_din <= q;
   u_0combo_proc: PROCESS (mw_U_0temp_din)
   VARIABLE temp_din: std_logic_vector(127 DOWNTO 0);
   BEGIN
      temp_din := mw_U_0temp_din(127 DOWNTO 0);
      dout0 <= temp_din(31 DOWNTO 0);
      dout1 <= temp_din(63 DOWNTO 32);
      dout2 <= temp_din(95 DOWNTO 64);
      dout3 <= temp_din(127 DOWNTO 96);
   END PROCESS u_0combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_1' of 'split'
   mw_U_1temp_din <= q1;
   u_1combo_proc: PROCESS (mw_U_1temp_din)
   VARIABLE temp_din: std_logic_vector(15 DOWNTO 0);
   BEGIN
      temp_din := mw_U_1temp_din(15 DOWNTO 0);
      dout4 <= temp_din(3 DOWNTO 0);
      dout5 <= temp_din(7 DOWNTO 4);
      dout6 <= temp_din(11 DOWNTO 8);
      dout7 <= temp_din(15 DOWNTO 12);
   END PROCESS u_1combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_2' of 'split'
   mw_U_2temp_din <= q2;
   u_2combo_proc: PROCESS (mw_U_2temp_din)
   VARIABLE temp_din: std_logic_vector(3 DOWNTO 0);
   BEGIN
      temp_din := mw_U_2temp_din(3 DOWNTO 0);
      dout8 <= temp_din(0);
      dout9 <= temp_din(1);
      dout10 <= temp_din(2);
      dout11 <= temp_din(3);
   END PROCESS u_2combo_proc;

   -- Instance port mappings.
   U_3 : aes_ctr_state_counter
      PORT MAP (
         advance   => dout14,
         clear     => clear,
         clk       => clk,
         reset_n   => reset_n,
         state_out => state_out
      );
   U_4 : aes_ctr_state_decoder
      PORT MAP (
         state_in       => state_out,
         state_is_busy  => serializer_busy_internal,
         state_is_idle  => state_is_idle,
         state_is_word1 => state_is_word1,
         state_is_word2 => state_is_word2,
         state_is_word3 => state_is_word3,
         state_is_word4 => state_is_word4
      );

   -- Implicit buffered output assignments
   m_axis_tlast    <= m_axis_tlast_internal;
   serializer_busy <= serializer_busy_internal;

END struct;
