-- VHDL Entity zybo_aes_hdl_lib.aes_sub_bytes.symbol
--
-- Created:
--          by - Shahin.UNKNOWN (DESKTOP-THSND8B)
--          at - 21:36:07 05/26/2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY aes_sub_bytes IS
   PORT( 
      sub_bytes_in  : IN     std_logic_vector (127 DOWNTO 0);
      sub_bytes_out : OUT    std_logic_vector (127 DOWNTO 0)
   );

-- Declarations

END aes_sub_bytes ;

--
-- VHDL Architecture zybo_aes_hdl_lib.aes_sub_bytes.struct
--
-- Created:
--          by - Shahin.UNKNOWN (DESKTOP-THSND8B)
--          at - 21:36:07 05/26/2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY zybo_aes_hdl_lib;

ARCHITECTURE struct OF aes_sub_bytes IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL byte_out   : std_logic_vector(7 DOWNTO 0);
   SIGNAL byte_out1  : std_logic_vector(7 DOWNTO 0);
   SIGNAL byte_out10 : std_logic_vector(7 DOWNTO 0);
   SIGNAL byte_out11 : std_logic_vector(7 DOWNTO 0);
   SIGNAL byte_out12 : std_logic_vector(7 DOWNTO 0);
   SIGNAL byte_out13 : std_logic_vector(7 DOWNTO 0);
   SIGNAL byte_out14 : std_logic_vector(7 DOWNTO 0);
   SIGNAL byte_out15 : std_logic_vector(7 DOWNTO 0);
   SIGNAL byte_out2  : std_logic_vector(7 DOWNTO 0);
   SIGNAL byte_out3  : std_logic_vector(7 DOWNTO 0);
   SIGNAL byte_out4  : std_logic_vector(7 DOWNTO 0);
   SIGNAL byte_out5  : std_logic_vector(7 DOWNTO 0);
   SIGNAL byte_out6  : std_logic_vector(7 DOWNTO 0);
   SIGNAL byte_out7  : std_logic_vector(7 DOWNTO 0);
   SIGNAL byte_out8  : std_logic_vector(7 DOWNTO 0);
   SIGNAL byte_out9  : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout0      : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout1      : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout10     : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout11     : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout12     : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout13     : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout14     : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout15     : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout2      : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout3      : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout4      : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout5      : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout6      : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout7      : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout8      : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout9      : std_logic_vector(7 DOWNTO 0);


   -- ModuleWare signal declarations(v1.12) for instance 'U_16' of 'split'
   SIGNAL mw_U_16temp_din : std_logic_vector(127 DOWNTO 0);

   -- Component Declarations
   COMPONENT aes_sbox
   PORT (
      byte_in  : IN     std_logic_vector (7 DOWNTO 0);
      byte_out : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : aes_sbox USE ENTITY zybo_aes_hdl_lib.aes_sbox;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_17' of 'merge'
   sub_bytes_out <= byte_out15 & byte_out14 & byte_out13 & byte_out12 & byte_out11 & byte_out10 & byte_out9 & byte_out8 & byte_out7 & byte_out6 & byte_out5 & byte_out4 & byte_out3 & byte_out2 & byte_out1 & byte_out;

   -- ModuleWare code(v1.12) for instance 'U_16' of 'split'
   mw_U_16temp_din <= sub_bytes_in;
   u_16combo_proc: PROCESS (mw_U_16temp_din)
   VARIABLE temp_din: std_logic_vector(127 DOWNTO 0);
   BEGIN
      temp_din := mw_U_16temp_din(127 DOWNTO 0);
      dout0 <= temp_din(7 DOWNTO 0);
      dout1 <= temp_din(15 DOWNTO 8);
      dout2 <= temp_din(23 DOWNTO 16);
      dout3 <= temp_din(31 DOWNTO 24);
      dout4 <= temp_din(39 DOWNTO 32);
      dout5 <= temp_din(47 DOWNTO 40);
      dout6 <= temp_din(55 DOWNTO 48);
      dout7 <= temp_din(63 DOWNTO 56);
      dout8 <= temp_din(71 DOWNTO 64);
      dout9 <= temp_din(79 DOWNTO 72);
      dout10 <= temp_din(87 DOWNTO 80);
      dout11 <= temp_din(95 DOWNTO 88);
      dout12 <= temp_din(103 DOWNTO 96);
      dout13 <= temp_din(111 DOWNTO 104);
      dout14 <= temp_din(119 DOWNTO 112);
      dout15 <= temp_din(127 DOWNTO 120);
   END PROCESS u_16combo_proc;

   -- Instance port mappings.
   U_0 : aes_sbox
      PORT MAP (
         byte_in  => dout0,
         byte_out => byte_out
      );
   U_1 : aes_sbox
      PORT MAP (
         byte_in  => dout1,
         byte_out => byte_out1
      );
   U_2 : aes_sbox
      PORT MAP (
         byte_in  => dout2,
         byte_out => byte_out2
      );
   U_3 : aes_sbox
      PORT MAP (
         byte_in  => dout3,
         byte_out => byte_out3
      );
   U_4 : aes_sbox
      PORT MAP (
         byte_in  => dout12,
         byte_out => byte_out12
      );
   U_5 : aes_sbox
      PORT MAP (
         byte_in  => dout13,
         byte_out => byte_out13
      );
   U_6 : aes_sbox
      PORT MAP (
         byte_in  => dout14,
         byte_out => byte_out14
      );
   U_7 : aes_sbox
      PORT MAP (
         byte_in  => dout15,
         byte_out => byte_out15
      );
   U_8 : aes_sbox
      PORT MAP (
         byte_in  => dout4,
         byte_out => byte_out4
      );
   U_9 : aes_sbox
      PORT MAP (
         byte_in  => dout5,
         byte_out => byte_out5
      );
   U_10 : aes_sbox
      PORT MAP (
         byte_in  => dout6,
         byte_out => byte_out6
      );
   U_11 : aes_sbox
      PORT MAP (
         byte_in  => dout7,
         byte_out => byte_out7
      );
   U_12 : aes_sbox
      PORT MAP (
         byte_in  => dout8,
         byte_out => byte_out8
      );
   U_13 : aes_sbox
      PORT MAP (
         byte_in  => dout9,
         byte_out => byte_out9
      );
   U_14 : aes_sbox
      PORT MAP (
         byte_in  => dout10,
         byte_out => byte_out10
      );
   U_15 : aes_sbox
      PORT MAP (
         byte_in  => dout11,
         byte_out => byte_out11
      );

END struct;
