-- VHDL Entity zybo_aes_hdl_lib.aes_shift_rows.symbol
--
-- Created:
--          by - Shahin.UNKNOWN (DESKTOP-THSND8B)
--          at - 23:05:30 05/24/2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY aes_shift_rows IS
   PORT( 
      shift_rows_in  : IN     std_logic_vector (127 DOWNTO 0);
      shift_rows_out : OUT    std_logic_vector (127 DOWNTO 0)
   );

-- Declarations

END aes_shift_rows ;

--
-- VHDL Architecture zybo_aes_hdl_lib.aes_shift_rows.struct
--
-- Created:
--          by - Shahin.UNKNOWN (DESKTOP-THSND8B)
--          at - 23:05:30 05/24/2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF aes_shift_rows IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL byte_0_0 : std_logic_vector(7 DOWNTO 0);
   SIGNAL byte_0_1 : std_logic_vector(7 DOWNTO 0);
   SIGNAL byte_0_2 : std_logic_vector(7 DOWNTO 0);
   SIGNAL byte_0_3 : std_logic_vector(7 DOWNTO 0);
   SIGNAL byte_1_0 : std_logic_vector(7 DOWNTO 0);
   SIGNAL byte_1_1 : std_logic_vector(7 DOWNTO 0);
   SIGNAL byte_1_2 : std_logic_vector(7 DOWNTO 0);
   SIGNAL byte_1_3 : std_logic_vector(7 DOWNTO 0);
   SIGNAL byte_2_0 : std_logic_vector(7 DOWNTO 0);
   SIGNAL byte_2_1 : std_logic_vector(7 DOWNTO 0);
   SIGNAL byte_2_2 : std_logic_vector(7 DOWNTO 0);
   SIGNAL byte_2_3 : std_logic_vector(7 DOWNTO 0);
   SIGNAL byte_3_0 : std_logic_vector(7 DOWNTO 0);
   SIGNAL byte_3_1 : std_logic_vector(7 DOWNTO 0);
   SIGNAL byte_3_2 : std_logic_vector(7 DOWNTO 0);
   SIGNAL byte_3_3 : std_logic_vector(7 DOWNTO 0);


   -- ModuleWare signal declarations(v1.12) for instance 'U_1' of 'split'
   SIGNAL mw_U_1temp_din : std_logic_vector(127 DOWNTO 0);


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_0' of 'merge'
   shift_rows_out <= byte_0_0 & byte_1_1 & byte_2_2 & byte_3_3 & byte_0_1 & byte_1_2 & byte_2_3 & byte_3_0 & byte_0_2 & byte_1_3 & byte_2_0 & byte_3_1 & byte_0_3 & byte_1_0 & byte_2_1 & byte_3_2;

   -- ModuleWare code(v1.12) for instance 'U_1' of 'split'
   mw_U_1temp_din <= shift_rows_in;
   u_1combo_proc: PROCESS (mw_U_1temp_din)
   VARIABLE temp_din: std_logic_vector(127 DOWNTO 0);
   BEGIN
      temp_din := mw_U_1temp_din(127 DOWNTO 0);
      byte_3_3 <= temp_din(7 DOWNTO 0);
      byte_2_3 <= temp_din(15 DOWNTO 8);
      byte_1_3 <= temp_din(23 DOWNTO 16);
      byte_0_3 <= temp_din(31 DOWNTO 24);
      byte_3_2 <= temp_din(39 DOWNTO 32);
      byte_2_2 <= temp_din(47 DOWNTO 40);
      byte_1_2 <= temp_din(55 DOWNTO 48);
      byte_0_2 <= temp_din(63 DOWNTO 56);
      byte_3_1 <= temp_din(71 DOWNTO 64);
      byte_2_1 <= temp_din(79 DOWNTO 72);
      byte_1_1 <= temp_din(87 DOWNTO 80);
      byte_0_1 <= temp_din(95 DOWNTO 88);
      byte_3_0 <= temp_din(103 DOWNTO 96);
      byte_2_0 <= temp_din(111 DOWNTO 104);
      byte_1_0 <= temp_din(119 DOWNTO 112);
      byte_0_0 <= temp_din(127 DOWNTO 120);
   END PROCESS u_1combo_proc;

   -- Instance port mappings.

END struct;
