-- VHDL Entity zybo_aes_hdl_lib.aes_ctr_counter_block.symbol
--
-- Created:
--          by - Shahin.UNKNOWN (DESKTOP-THSND8B)
--          at - 19:37:47 05/29/2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY aes_ctr_counter_block IS
   PORT( 
      clk                  : IN     std_logic;
      initial_counter_in   : IN     std_logic_vector (31 DOWNTO 0);
      load_initial_counter : IN     std_logic;
      next_block           : IN     std_logic;
      nonce_in             : IN     std_logic_vector (95 DOWNTO 0);
      reset_n              : IN     std_logic;
      counter_block_out    : OUT    std_logic_vector (127 DOWNTO 0)
   );

-- Declarations

END aes_ctr_counter_block ;

--
-- VHDL Architecture zybo_aes_hdl_lib.aes_ctr_counter_block.struct
--
-- Created:
--          by - Shahin.UNKNOWN (DESKTOP-THSND8B)
--          at - 19:37:47 05/29/2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF aes_ctr_counter_block IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout  : std_logic_vector(31 DOWNTO 0);
   SIGNAL dout1 : std_logic_vector(31 DOWNTO 0);
   SIGNAL q     : std_logic_vector(31 DOWNTO 0);


   -- ModuleWare signal declarations(v1.12) for instance 'U_0' of 'adff'
   SIGNAL mw_U_0reg_cval : std_logic_vector(31 DOWNTO 0);


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_0' of 'adff'
   q <= mw_U_0reg_cval;
   u_0seq_proc: PROCESS (clk)BEGIN
      IF (clk'EVENT AND clk='1') THEN
         IF (reset_n = '0') THEN
            mw_U_0reg_cval <= x"00000000";
         ELSIF (next_block = '1') THEN
            mw_U_0reg_cval <= dout;
         END IF;
      END IF;
   END PROCESS u_0seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_2' of 'inc'
   u_2combo_proc: PROCESS (q)
   VARIABLE temp_din : std_logic_vector(32 DOWNTO 0);
   VARIABLE temp_sum : unsigned(32 DOWNTO 0);
   BEGIN
      temp_din := '0' & q;
      temp_sum := (unsigned(temp_din) + '1');
      dout1 <= conv_std_logic_vector(temp_sum(31 DOWNTO 0),32);
   END PROCESS u_2combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_3' of 'merge'
   counter_block_out <= nonce_in & q;

   -- ModuleWare code(v1.12) for instance 'U_1' of 'mux'
   u_1combo_proc: PROCESS(dout1, initial_counter_in, 
                          load_initial_counter)
   BEGIN
      CASE load_initial_counter IS
      WHEN '0' => dout <= dout1;
      WHEN '1' => dout <= initial_counter_in;
      WHEN OTHERS => dout <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_1combo_proc;

   -- Instance port mappings.

END struct;
