-- VHDL Entity zybo_aes_hdl_lib.aes_rot_sub_word.symbol
--
-- Created:
--          by - Shahin.UNKNOWN (DESKTOP-THSND8B)
--          at - 17:08:02 05/25/2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY aes_rot_sub_word IS
   PORT( 
      aes_rot_sub_word_in  : IN     std_logic_vector (31 DOWNTO 0);
      aes_rot_sub_word_out : OUT    std_logic_vector (31 DOWNTO 0)
   );

-- Declarations

END aes_rot_sub_word ;

--
-- VHDL Architecture zybo_aes_hdl_lib.aes_rot_sub_word.struct
--
-- Created:
--          by - Shahin.UNKNOWN (DESKTOP-THSND8B)
--          at - 16:06:38 05/27/2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY zybo_aes_hdl_lib;

ARCHITECTURE struct OF aes_rot_sub_word IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL byte_out  : std_logic_vector(7 DOWNTO 0);
   SIGNAL byte_out1 : std_logic_vector(7 DOWNTO 0);
   SIGNAL byte_out2 : std_logic_vector(7 DOWNTO 0);
   SIGNAL byte_out3 : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout0     : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout1     : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout2     : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout3     : std_logic_vector(7 DOWNTO 0);


   -- ModuleWare signal declarations(v1.12) for instance 'U_0' of 'split'
   SIGNAL mw_U_0temp_din : std_logic_vector(31 DOWNTO 0);

   -- Component Declarations
   COMPONENT aes_sbox
   PORT (
      byte_in  : IN     std_logic_vector (7 DOWNTO 0);
      byte_out : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : aes_sbox USE ENTITY zybo_aes_hdl_lib.aes_sbox;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_1' of 'merge'
   aes_rot_sub_word_out <= byte_out3 & byte_out2 & byte_out1 & byte_out;

   -- ModuleWare code(v1.12) for instance 'U_0' of 'split'
   mw_U_0temp_din <= aes_rot_sub_word_in;
   u_0combo_proc: PROCESS (mw_U_0temp_din)
   VARIABLE temp_din: std_logic_vector(31 DOWNTO 0);
   BEGIN
      temp_din := mw_U_0temp_din(31 DOWNTO 0);
      dout0 <= temp_din(7 DOWNTO 0);
      dout1 <= temp_din(15 DOWNTO 8);
      dout2 <= temp_din(23 DOWNTO 16);
      dout3 <= temp_din(31 DOWNTO 24);
   END PROCESS u_0combo_proc;

   -- Instance port mappings.
   U_2 : aes_sbox
      PORT MAP (
         byte_in  => dout3,
         byte_out => byte_out
      );
   U_3 : aes_sbox
      PORT MAP (
         byte_in  => dout0,
         byte_out => byte_out1
      );
   U_4 : aes_sbox
      PORT MAP (
         byte_in  => dout2,
         byte_out => byte_out3
      );
   U_5 : aes_sbox
      PORT MAP (
         byte_in  => dout1,
         byte_out => byte_out2
      );

END struct;
