-- VHDL Entity zybo_aes_hdl_lib.aes_ctr_state_counter.symbol
--
-- Created:
--          by - Shahin.UNKNOWN (DESKTOP-THSND8B)
--          at - 13:18:53 06/ 8/2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY aes_ctr_state_counter IS
   PORT( 
      advance   : IN     std_logic;
      clear     : IN     std_logic;
      clk       : IN     std_logic;
      reset_n   : IN     std_logic;
      state_out : OUT    std_logic_vector (2 DOWNTO 0)
   );

-- Declarations

END aes_ctr_state_counter ;

--
-- VHDL Architecture zybo_aes_hdl_lib.aes_ctr_state_counter.struct
--
-- Created:
--          by - Shahin.UNKNOWN (DESKTOP-THSND8B)
--          at - 13:18:53 06/ 8/2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF aes_ctr_state_counter IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout  : std_logic_vector(2 DOWNTO 0);
   SIGNAL dout1 : std_logic_vector(2 DOWNTO 0);
   SIGNAL dout2 : std_logic_vector(2 DOWNTO 0);

   -- Implicit buffer signal declarations
   SIGNAL state_out_internal : std_logic_vector (2 DOWNTO 0);


   -- ModuleWare signal declarations(v1.12) for instance 'U_5' of 'adff'
   SIGNAL mw_U_5reg_cval : std_logic_vector(2 DOWNTO 0);


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_5' of 'adff'
   state_out_internal <= mw_U_5reg_cval;
   u_5seq_proc: PROCESS (clk)BEGIN
      IF (clk'EVENT AND clk='1') THEN
         IF (reset_n = '0') THEN
            mw_U_5reg_cval <= "000";
         ELSIF (advance = '1') THEN
            mw_U_5reg_cval <= dout;
         END IF;
      END IF;
   END PROCESS u_5seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_49' of 'constval'
   dout2 <= "000";

   -- ModuleWare code(v1.12) for instance 'U_4' of 'inc'
   u_4combo_proc: PROCESS (state_out_internal)
   VARIABLE temp_din : std_logic_vector(3 DOWNTO 0);
   VARIABLE temp_sum : unsigned(3 DOWNTO 0);
   BEGIN
      temp_din := '0' & state_out_internal;
      temp_sum := (unsigned(temp_din) + '1');
      dout1 <= conv_std_logic_vector(temp_sum(2 DOWNTO 0),3);
   END PROCESS u_4combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_48' of 'mux'
   u_48combo_proc: PROCESS(dout1, dout2, clear)
   BEGIN
      CASE clear IS
      WHEN '0' => dout <= dout1;
      WHEN '1' => dout <= dout2;
      WHEN OTHERS => dout <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_48combo_proc;

   -- Instance port mappings.

   -- Implicit buffered output assignments
   state_out <= state_out_internal;

END struct;
