-- VHDL Entity zybo_aes_hdl_lib.aes_key_expand_round.symbol
--
-- Created:
--          by - Shahin.UNKNOWN (DESKTOP-THSND8B)
--          at - 16:11:41 05/27/2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY aes_key_expand_round IS
   PORT( 
      key_expand_round_in  : IN     std_logic_vector (127 DOWNTO 0);
      round_index          : IN     std_logic_vector (3 DOWNTO 0);
      key_expand_round_out : OUT    std_logic_vector (127 DOWNTO 0)
   );

-- Declarations

END aes_key_expand_round ;

--
-- VHDL Architecture zybo_aes_hdl_lib.aes_key_expand_round.struct
--
-- Created:
--          by - Shahin.UNKNOWN (DESKTOP-THSND8B)
--          at - 16:11:41 05/27/2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY zybo_aes_hdl_lib;

ARCHITECTURE struct OF aes_key_expand_round IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL aes_rot_sub_word_out        : std_logic_vector(31 DOWNTO 0);
   SIGNAL key_expand_round_in_word_0  : std_logic_vector(31 DOWNTO 0);
   SIGNAL key_expand_round_in_word_1  : std_logic_vector(31 DOWNTO 0);
   SIGNAL key_expand_round_in_word_2  : std_logic_vector(31 DOWNTO 0);
   SIGNAL key_expand_round_in_word_3  : std_logic_vector(31 DOWNTO 0);
   SIGNAL key_expand_round_out_word_0 : std_logic_vector(31 DOWNTO 0);
   SIGNAL key_expand_round_out_word_1 : std_logic_vector(31 DOWNTO 0);
   SIGNAL key_expand_round_out_word_2 : std_logic_vector(31 DOWNTO 0);
   SIGNAL key_expand_round_out_word_3 : std_logic_vector(31 DOWNTO 0);
   SIGNAL rcon                        : std_logic_vector(31 DOWNTO 0);


   -- ModuleWare signal declarations(v1.12) for instance 'U_5' of 'split'
   SIGNAL mw_U_5temp_din : std_logic_vector(127 DOWNTO 0);

   -- Component Declarations
   COMPONENT aes_rcon
   PORT (
      round_index : IN     std_logic_vector (3 DOWNTO 0);
      rcon        : OUT    std_logic_vector (31 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT aes_rot_sub_word
   PORT (
      aes_rot_sub_word_in  : IN     std_logic_vector (31 DOWNTO 0);
      aes_rot_sub_word_out : OUT    std_logic_vector (31 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : aes_rcon USE ENTITY zybo_aes_hdl_lib.aes_rcon;
   FOR ALL : aes_rot_sub_word USE ENTITY zybo_aes_hdl_lib.aes_rot_sub_word;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_6' of 'merge'
   key_expand_round_out <= key_expand_round_out_word_0 & key_expand_round_out_word_1 & key_expand_round_out_word_2 & key_expand_round_out_word_3;

   -- ModuleWare code(v1.12) for instance 'U_5' of 'split'
   mw_U_5temp_din <= key_expand_round_in;
   u_5combo_proc: PROCESS (mw_U_5temp_din)
   VARIABLE temp_din: std_logic_vector(127 DOWNTO 0);
   BEGIN
      temp_din := mw_U_5temp_din(127 DOWNTO 0);
      key_expand_round_in_word_3 <= temp_din(31 DOWNTO 0);
      key_expand_round_in_word_2 <= temp_din(63 DOWNTO 32);
      key_expand_round_in_word_1 <= temp_din(95 DOWNTO 64);
      key_expand_round_in_word_0 <= temp_din(127 DOWNTO 96);
   END PROCESS u_5combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_0' of 'xor'
   key_expand_round_out_word_0 <= key_expand_round_in_word_0
                                  XOR aes_rot_sub_word_out XOR rcon;

   -- ModuleWare code(v1.12) for instance 'U_1' of 'xor'
   key_expand_round_out_word_1 <= key_expand_round_out_word_0
                                  XOR key_expand_round_in_word_1;

   -- ModuleWare code(v1.12) for instance 'U_2' of 'xor'
   key_expand_round_out_word_2 <= key_expand_round_out_word_1
                                  XOR key_expand_round_in_word_2;

   -- ModuleWare code(v1.12) for instance 'U_3' of 'xor'
   key_expand_round_out_word_3 <= key_expand_round_out_word_2
                                  XOR key_expand_round_in_word_3;

   -- Instance port mappings.
   U_7 : aes_rcon
      PORT MAP (
         round_index => round_index,
         rcon        => rcon
      );
   U_4 : aes_rot_sub_word
      PORT MAP (
         aes_rot_sub_word_in  => key_expand_round_in_word_3,
         aes_rot_sub_word_out => aes_rot_sub_word_out
      );

END struct;
