-- VHDL Entity zybo_aes_hdl_lib.aes_ctr_state_decoder.symbol
--
-- Created:
--          by - Shahin.UNKNOWN (DESKTOP-THSND8B)
--          at - 20:37:59 06/14/2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY aes_ctr_state_decoder IS
   PORT( 
      state_in       : IN     std_logic_vector (2 DOWNTO 0);
      state_is_busy  : OUT    std_logic;
      state_is_idle  : OUT    std_logic;
      state_is_word1 : OUT    std_logic;
      state_is_word2 : OUT    std_logic;
      state_is_word3 : OUT    std_logic;
      state_is_word4 : OUT    std_logic
   );

-- Declarations

END aes_ctr_state_decoder ;

--
-- VHDL Architecture zybo_aes_hdl_lib.aes_ctr_state_decoder.struct
--
-- Created:
--          by - Shahin.UNKNOWN (DESKTOP-THSND8B)
--          at - 20:37:59 06/14/2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF aes_ctr_state_decoder IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout  : std_logic_vector(2 DOWNTO 0);
   SIGNAL dout1 : std_logic_vector(2 DOWNTO 0);
   SIGNAL dout2 : std_logic_vector(2 DOWNTO 0);
   SIGNAL dout3 : std_logic_vector(2 DOWNTO 0);
   SIGNAL dout4 : std_logic_vector(2 DOWNTO 0);
   SIGNAL dout5 : std_logic_vector(2 DOWNTO 0);
   SIGNAL dout6 : std_logic_vector(2 DOWNTO 0);
   SIGNAL dout7 : std_logic_vector(2 DOWNTO 0);
   SIGNAL dout8 : std_logic_vector(2 DOWNTO 0);
   SIGNAL dout9 : std_logic_vector(2 DOWNTO 0);

   -- Implicit buffer signal declarations
   SIGNAL state_is_idle_internal : std_logic;



BEGIN

   -- ModuleWare code(v1.12) for instance 'U_9' of 'constval'
   dout8 <= "100";

   -- ModuleWare code(v1.12) for instance 'U_10' of 'constval'
   dout6 <= "011";

   -- ModuleWare code(v1.12) for instance 'U_14' of 'constval'
   dout4 <= "010";

   -- ModuleWare code(v1.12) for instance 'U_18' of 'constval'
   dout2 <= "001";

   -- ModuleWare code(v1.12) for instance 'U_44' of 'constval'
   dout <= "000";

   -- ModuleWare code(v1.12) for instance 'U_0' of 'inv'
   state_is_busy <= NOT(state_is_idle_internal);

   -- ModuleWare code(v1.12) for instance 'U_7' of 'tand'
   state_is_word4 <= dout9(0) AND dout9(1) AND dout9(2);

   -- ModuleWare code(v1.12) for instance 'U_8' of 'tand'
   state_is_word3 <= dout7(0) AND dout7(1) AND dout7(2);

   -- ModuleWare code(v1.12) for instance 'U_12' of 'tand'
   state_is_word2 <= dout5(0) AND dout5(1) AND dout5(2);

   -- ModuleWare code(v1.12) for instance 'U_13' of 'tand'
   state_is_word1 <= dout3(0) AND dout3(1) AND dout3(2);

   -- ModuleWare code(v1.12) for instance 'U_46' of 'tand'
   state_is_idle_internal <= dout1(0) AND dout1(1) AND dout1(2);

   -- ModuleWare code(v1.12) for instance 'U_22' of 'xnor'
   dout9 <= NOT(state_in XOR dout8);

   -- ModuleWare code(v1.12) for instance 'U_23' of 'xnor'
   dout7 <= NOT(state_in XOR dout6);

   -- ModuleWare code(v1.12) for instance 'U_24' of 'xnor'
   dout5 <= NOT(state_in XOR dout4);

   -- ModuleWare code(v1.12) for instance 'U_25' of 'xnor'
   dout3 <= NOT(state_in XOR dout2);

   -- ModuleWare code(v1.12) for instance 'U_45' of 'xnor'
   dout1 <= NOT(state_in XOR dout);

   -- Instance port mappings.

   -- Implicit buffered output assignments
   state_is_idle <= state_is_idle_internal;

END struct;
