-- VHDL Entity zybo_aes_hdl_lib.aes_ctr_input_collector.symbol
--
-- Created:
--          by - Shahin.UNKNOWN (DESKTOP-THSND8B)
--          at - 23:43:34 06/14/2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY aes_ctr_input_collector IS
   PORT( 
      clk                      : IN     std_logic;
      keep_in                  : IN     std_logic_vector (3 DOWNTO 0);
      last_in                  : IN     std_logic;
      reset_n                  : IN     std_logic;
      start_collector          : IN     std_logic;
      word_in                  : IN     std_logic_vector (31 DOWNTO 0);
      word_valid               : IN     std_logic;
      block_out                : OUT    std_logic_vector (127 DOWNTO 0);
      collector_done           : OUT    std_logic;
      collector_ready_for_word : OUT    std_logic;
      keep_block_out           : OUT    std_logic_vector (15 DOWNTO 0);
      last_word_mask_out       : OUT    std_logic_vector (3 DOWNTO 0)
   );

-- Declarations

END aes_ctr_input_collector ;

--
-- VHDL Architecture zybo_aes_hdl_lib.aes_ctr_input_collector.struct
--
-- Created:
--          by - Shahin.UNKNOWN (DESKTOP-THSND8B)
--          at - 23:43:34 06/14/2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY zybo_aes_hdl_lib;

ARCHITECTURE struct OF aes_ctr_input_collector IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL continue  : std_logic;
   SIGNAL din2      : std_logic;
   SIGNAL dout10    : std_logic;
   SIGNAL dout12    : std_logic;
   SIGNAL dout13    : std_logic;
   SIGNAL dout14    : std_logic;
   SIGNAL dout15    : std_logic;
   SIGNAL dout16    : std_logic;
   SIGNAL dout17    : std_logic;
   SIGNAL dout19    : std_logic;
   SIGNAL dout20    : std_logic;
   SIGNAL dout21    : std_logic;
   SIGNAL dout22    : std_logic;
   SIGNAL dout23    : std_logic;
   SIGNAL dout24    : std_logic;
   SIGNAL dout25    : std_logic_vector(31 DOWNTO 0);
   SIGNAL dout26    : std_logic_vector(3 DOWNTO 0);
   SIGNAL dout27    : std_logic;
   SIGNAL dout28    : std_logic;
   SIGNAL dout29    : std_logic;
   SIGNAL dout30    : std_logic;
   SIGNAL dout32    : std_logic_vector(3 DOWNTO 0);
   SIGNAL dout33    : std_logic_vector(3 DOWNTO 0);
   SIGNAL dout34    : std_logic_vector(3 DOWNTO 0);
   SIGNAL keep_data : std_logic_vector(3 DOWNTO 0);
   SIGNAL q         : std_logic_vector(2 DOWNTO 0);
   SIGNAL q1        : std_logic_vector(31 DOWNTO 0);
   SIGNAL q2        : std_logic_vector(31 DOWNTO 0);
   SIGNAL q3        : std_logic_vector(31 DOWNTO 0);
   SIGNAL q4        : std_logic_vector(31 DOWNTO 0);
   SIGNAL q5        : std_logic_vector(3 DOWNTO 0);
   SIGNAL q6        : std_logic_vector(3 DOWNTO 0);
   SIGNAL q7        : std_logic_vector(3 DOWNTO 0);
   SIGNAL q8        : std_logic_vector(3 DOWNTO 0);
   SIGNAL word_data : std_logic_vector(31 DOWNTO 0);

   -- Implicit buffer signal declarations
   SIGNAL collector_ready_for_word_internal : std_logic;


   -- ModuleWare signal declarations(v1.12) for instance 'U_0' of 'adff'
   SIGNAL mw_U_0reg_cval : std_logic_vector(31 DOWNTO 0);

   -- ModuleWare signal declarations(v1.12) for instance 'U_1' of 'adff'
   SIGNAL mw_U_1reg_cval : std_logic_vector(31 DOWNTO 0);

   -- ModuleWare signal declarations(v1.12) for instance 'U_2' of 'adff'
   SIGNAL mw_U_2reg_cval : std_logic_vector(31 DOWNTO 0);

   -- ModuleWare signal declarations(v1.12) for instance 'U_3' of 'adff'
   SIGNAL mw_U_3reg_cval : std_logic_vector(31 DOWNTO 0);

   -- ModuleWare signal declarations(v1.12) for instance 'U_29' of 'adff'
   SIGNAL mw_U_29reg_cval : std_logic_vector(3 DOWNTO 0);

   -- ModuleWare signal declarations(v1.12) for instance 'U_30' of 'adff'
   SIGNAL mw_U_30reg_cval : std_logic_vector(3 DOWNTO 0);

   -- ModuleWare signal declarations(v1.12) for instance 'U_31' of 'adff'
   SIGNAL mw_U_31reg_cval : std_logic_vector(3 DOWNTO 0);

   -- ModuleWare signal declarations(v1.12) for instance 'U_32' of 'adff'
   SIGNAL mw_U_32reg_cval : std_logic_vector(3 DOWNTO 0);

   -- ModuleWare signal declarations(v1.12) for instance 'U_40' of 'adff'
   SIGNAL mw_U_40reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.12) for instance 'U_47' of 'adff'
   SIGNAL mw_U_47reg_cval : std_logic_vector(3 DOWNTO 0);

   -- Component Declarations
   COMPONENT aes_ctr_state_counter
   PORT (
      advance   : IN     std_logic ;
      clear     : IN     std_logic ;
      clk       : IN     std_logic ;
      reset_n   : IN     std_logic ;
      state_out : OUT    std_logic_vector (2 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT aes_ctr_state_decoder
   PORT (
      state_in       : IN     std_logic_vector (2 DOWNTO 0);
      state_is_busy  : OUT    std_logic ;
      state_is_idle  : OUT    std_logic ;
      state_is_word1 : OUT    std_logic ;
      state_is_word2 : OUT    std_logic ;
      state_is_word3 : OUT    std_logic ;
      state_is_word4 : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : aes_ctr_state_counter USE ENTITY zybo_aes_hdl_lib.aes_ctr_state_counter;
   FOR ALL : aes_ctr_state_decoder USE ENTITY zybo_aes_hdl_lib.aes_ctr_state_decoder;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_0' of 'adff'
   q1 <= mw_U_0reg_cval;
   u_0seq_proc: PROCESS (clk)BEGIN
      IF (clk'EVENT AND clk='1') THEN
         IF (reset_n = '0') THEN
            mw_U_0reg_cval <= x"00000000";
         ELSIF (dout15 = '1') THEN
            mw_U_0reg_cval <= word_data;
         END IF;
      END IF;
   END PROCESS u_0seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_1' of 'adff'
   q2 <= mw_U_1reg_cval;
   u_1seq_proc: PROCESS (clk)BEGIN
      IF (clk'EVENT AND clk='1') THEN
         IF (reset_n = '0') THEN
            mw_U_1reg_cval <= x"00000000";
         ELSIF (dout19 = '1') THEN
            mw_U_1reg_cval <= word_data;
         END IF;
      END IF;
   END PROCESS u_1seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_2' of 'adff'
   q3 <= mw_U_2reg_cval;
   u_2seq_proc: PROCESS (clk)BEGIN
      IF (clk'EVENT AND clk='1') THEN
         IF (reset_n = '0') THEN
            mw_U_2reg_cval <= x"00000000";
         ELSIF (dout20 = '1') THEN
            mw_U_2reg_cval <= word_data;
         END IF;
      END IF;
   END PROCESS u_2seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_3' of 'adff'
   q4 <= mw_U_3reg_cval;
   u_3seq_proc: PROCESS (clk)BEGIN
      IF (clk'EVENT AND clk='1') THEN
         IF (reset_n = '0') THEN
            mw_U_3reg_cval <= x"00000000";
         ELSIF (dout21 = '1') THEN
            mw_U_3reg_cval <= word_data;
         END IF;
      END IF;
   END PROCESS u_3seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_29' of 'adff'
   q5 <= mw_U_29reg_cval;
   u_29seq_proc: PROCESS (clk)BEGIN
      IF (clk'EVENT AND clk='1') THEN
         IF (reset_n = '0') THEN
            mw_U_29reg_cval <= "0000";
         ELSIF (dout15 = '1') THEN
            mw_U_29reg_cval <= keep_data;
         END IF;
      END IF;
   END PROCESS u_29seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_30' of 'adff'
   q6 <= mw_U_30reg_cval;
   u_30seq_proc: PROCESS (clk)BEGIN
      IF (clk'EVENT AND clk='1') THEN
         IF (reset_n = '0') THEN
            mw_U_30reg_cval <= "0000";
         ELSIF (dout19 = '1') THEN
            mw_U_30reg_cval <= keep_data;
         END IF;
      END IF;
   END PROCESS u_30seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_31' of 'adff'
   q7 <= mw_U_31reg_cval;
   u_31seq_proc: PROCESS (clk)BEGIN
      IF (clk'EVENT AND clk='1') THEN
         IF (reset_n = '0') THEN
            mw_U_31reg_cval <= "0000";
         ELSIF (dout20 = '1') THEN
            mw_U_31reg_cval <= keep_data;
         END IF;
      END IF;
   END PROCESS u_31seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_32' of 'adff'
   q8 <= mw_U_32reg_cval;
   u_32seq_proc: PROCESS (clk)BEGIN
      IF (clk'EVENT AND clk='1') THEN
         IF (reset_n = '0') THEN
            mw_U_32reg_cval <= "0000";
         ELSIF (dout21 = '1') THEN
            mw_U_32reg_cval <= keep_data;
         END IF;
      END IF;
   END PROCESS u_32seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_40' of 'adff'
   collector_done <= mw_U_40reg_cval;
   u_40seq_proc: PROCESS (clk)BEGIN
      IF (clk'EVENT AND clk='1') THEN
         IF (reset_n = '0') THEN
            mw_U_40reg_cval <= '0';
         ELSE
            mw_U_40reg_cval <= dout27;
         END IF;
      END IF;
   END PROCESS u_40seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_47' of 'adff'
   last_word_mask_out <= mw_U_47reg_cval;
   u_47seq_proc: PROCESS (clk)BEGIN
      IF (clk'EVENT AND clk='1') THEN
         IF (reset_n = '0') THEN
            mw_U_47reg_cval <= "0000";
         ELSIF (dout29 = '1') THEN
            mw_U_47reg_cval <= dout33;
         END IF;
      END IF;
   END PROCESS u_47seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_11' of 'and'
   dout13 <= dout14 AND dout28;

   -- ModuleWare code(v1.12) for instance 'U_15' of 'and'
   dout22 <= dout16 AND dout28;

   -- ModuleWare code(v1.12) for instance 'U_19' of 'and'
   dout23 <= dout17 AND dout28;

   -- ModuleWare code(v1.12) for instance 'U_21' of 'and'
   dout12 <= last_in AND dout28;

   -- ModuleWare code(v1.12) for instance 'U_26' of 'and'
   dout24 <= dout10 AND dout28;

   -- ModuleWare code(v1.12) for instance 'U_43' of 'and'
   dout28 <= word_valid AND collector_ready_for_word_internal;

   -- ModuleWare code(v1.12) for instance 'U_50' of 'and'
   dout30 <= start_collector AND din2;

   -- ModuleWare code(v1.12) for instance 'U_38' of 'constval'
   dout25 <= x"00000000";

   -- ModuleWare code(v1.12) for instance 'U_39' of 'constval'
   dout26 <= "0000";

   -- ModuleWare code(v1.12) for instance 'U_52' of 'constval'
   dout32 <= "0000";

   -- ModuleWare code(v1.12) for instance 'U_6' of 'merge'
   block_out <= q4 & q3 & q2 & q1;

   -- ModuleWare code(v1.12) for instance 'U_33' of 'merge'
   keep_block_out <= q8 & q7 & q6 & q5;

   -- ModuleWare code(v1.12) for instance 'U_54' of 'merge'
   dout34 <= dout21 & dout20 & dout19 & dout15;

   -- ModuleWare code(v1.12) for instance 'U_36' of 'mux'
   u_36combo_proc: PROCESS(word_in, dout25, dout30)
   BEGIN
      CASE dout30 IS
      WHEN '0' => word_data <= word_in;
      WHEN '1' => word_data <= dout25;
      WHEN OTHERS => word_data <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_36combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_37' of 'mux'
   u_37combo_proc: PROCESS(keep_in, dout26, dout30)
   BEGIN
      CASE dout30 IS
      WHEN '0' => keep_data <= keep_in;
      WHEN '1' => keep_data <= dout26;
      WHEN OTHERS => keep_data <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_37combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_51' of 'mux'
   u_51combo_proc: PROCESS(dout32, dout34, dout12)
   BEGIN
      CASE dout12 IS
      WHEN '0' => dout33 <= dout32;
      WHEN '1' => dout33 <= dout34;
      WHEN OTHERS => dout33 <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_51combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_27' of 'or'
   dout15 <= dout30 OR dout13;

   -- ModuleWare code(v1.12) for instance 'U_28' of 'or'
   dout19 <= dout30 OR dout22;

   -- ModuleWare code(v1.12) for instance 'U_34' of 'or'
   dout20 <= dout30 OR dout23;

   -- ModuleWare code(v1.12) for instance 'U_35' of 'or'
   dout21 <= dout30 OR dout24;

   -- ModuleWare code(v1.12) for instance 'U_41' of 'or'
   dout27 <= dout12 OR dout13;

   -- ModuleWare code(v1.12) for instance 'U_42' of 'or'
   continue <= dout28 OR dout30;

   -- ModuleWare code(v1.12) for instance 'U_53' of 'or'
   dout29 <= dout30 OR dout12;

   -- Instance port mappings.
   U_4 : aes_ctr_state_counter
      PORT MAP (
         advance   => continue,
         clear     => dout27,
         clk       => clk,
         reset_n   => reset_n,
         state_out => q
      );
   U_5 : aes_ctr_state_decoder
      PORT MAP (
         state_in       => q,
         state_is_busy  => collector_ready_for_word_internal,
         state_is_idle  => din2,
         state_is_word1 => dout10,
         state_is_word2 => dout17,
         state_is_word3 => dout16,
         state_is_word4 => dout14
      );

   -- Implicit buffered output assignments
   collector_ready_for_word <= collector_ready_for_word_internal;

END struct;
