-- VHDL Entity zybo_aes_hdl_lib.aes_mix_column.symbol
--
-- Created:
--          by - Shahin.UNKNOWN (DESKTOP-THSND8B)
--          at - 22:05:32 05/24/2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY aes_mix_column IS
   PORT( 
      mix_column_in_row_0  : IN     std_logic_vector (7 DOWNTO 0);
      mix_column_in_row_1  : IN     std_logic_vector (7 DOWNTO 0);
      mix_column_in_row_2  : IN     std_logic_vector (7 DOWNTO 0);
      mix_column_in_row_3  : IN     std_logic_vector (7 DOWNTO 0);
      mix_column_out_row_0 : OUT    std_logic_vector (7 DOWNTO 0);
      mix_column_out_row_1 : OUT    std_logic_vector (7 DOWNTO 0);
      mix_column_out_row_2 : OUT    std_logic_vector (7 DOWNTO 0);
      mix_column_out_row_3 : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END aes_mix_column ;

--
-- VHDL Architecture zybo_aes_hdl_lib.aes_mix_column.struct
--
-- Created:
--          by - Shahin.UNKNOWN (DESKTOP-THSND8B)
--          at - 22:05:32 05/24/2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY zybo_aes_hdl_lib;

ARCHITECTURE struct OF aes_mix_column IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL mix_column_row_0_mul_2 : std_logic_vector(7 DOWNTO 0);
   SIGNAL mix_column_row_0_mul_3 : std_logic_vector(7 DOWNTO 0);
   SIGNAL mix_column_row_1_mul_2 : std_logic_vector(7 DOWNTO 0);
   SIGNAL mix_column_row_1_mul_3 : std_logic_vector(7 DOWNTO 0);
   SIGNAL mix_column_row_2_mul_2 : std_logic_vector(7 DOWNTO 0);
   SIGNAL mix_column_row_2_mul_3 : std_logic_vector(7 DOWNTO 0);
   SIGNAL mix_column_row_3_mul_2 : std_logic_vector(7 DOWNTO 0);
   SIGNAL mix_column_row_3_mul_3 : std_logic_vector(7 DOWNTO 0);


   -- Component Declarations
   COMPONENT aes_mul02
   PORT (
      mul_02_in  : IN     std_logic_vector (7 DOWNTO 0);
      mul_02_out : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT aes_mul03
   PORT (
      mul_03_in  : IN     std_logic_vector (7 DOWNTO 0);
      mul_03_out : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : aes_mul02 USE ENTITY zybo_aes_hdl_lib.aes_mul02;
   FOR ALL : aes_mul03 USE ENTITY zybo_aes_hdl_lib.aes_mul03;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_8' of 'xor'
   mix_column_out_row_0 <= mix_column_row_0_mul_2
                           XOR mix_column_row_1_mul_3
                           XOR mix_column_in_row_2
                           XOR mix_column_in_row_3;

   -- ModuleWare code(v1.12) for instance 'U_9' of 'xor'
   mix_column_out_row_1 <= mix_column_in_row_0 XOR mix_column_row_1_mul_2
                           XOR mix_column_row_2_mul_3
                           XOR mix_column_in_row_3;

   -- ModuleWare code(v1.12) for instance 'U_10' of 'xor'
   mix_column_out_row_2 <= mix_column_in_row_0 XOR mix_column_in_row_1
                           XOR mix_column_row_2_mul_2
                           XOR mix_column_row_3_mul_3;

   -- ModuleWare code(v1.12) for instance 'U_11' of 'xor'
   mix_column_out_row_3 <= mix_column_row_0_mul_3 XOR mix_column_in_row_1
                           XOR mix_column_in_row_2
                           XOR mix_column_row_3_mul_2;

   -- Instance port mappings.
   U_0 : aes_mul02
      PORT MAP (
         mul_02_in  => mix_column_in_row_0,
         mul_02_out => mix_column_row_0_mul_2
      );
   U_1 : aes_mul02
      PORT MAP (
         mul_02_in  => mix_column_in_row_1,
         mul_02_out => mix_column_row_1_mul_2
      );
   U_2 : aes_mul02
      PORT MAP (
         mul_02_in  => mix_column_in_row_2,
         mul_02_out => mix_column_row_2_mul_2
      );
   U_3 : aes_mul02
      PORT MAP (
         mul_02_in  => mix_column_in_row_3,
         mul_02_out => mix_column_row_3_mul_2
      );
   U_4 : aes_mul03
      PORT MAP (
         mul_03_in  => mix_column_in_row_0,
         mul_03_out => mix_column_row_0_mul_3
      );
   U_5 : aes_mul03
      PORT MAP (
         mul_03_in  => mix_column_in_row_1,
         mul_03_out => mix_column_row_1_mul_3
      );
   U_6 : aes_mul03
      PORT MAP (
         mul_03_in  => mix_column_in_row_2,
         mul_03_out => mix_column_row_2_mul_3
      );
   U_7 : aes_mul03
      PORT MAP (
         mul_03_in  => mix_column_in_row_3,
         mul_03_out => mix_column_row_3_mul_3
      );

END struct;
