-- VHDL Entity zybo_aes_hdl_lib.aes_mix_columns.symbol
--
-- Created:
--          by - Shahin.UNKNOWN (DESKTOP-THSND8B)
--          at - 15:23:04 05/27/2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY aes_mix_columns IS
   PORT( 
      columns_in    : IN     std_logic_vector (127 DOWNTO 0);
      columns_mixed : OUT    std_logic_vector (127 DOWNTO 0)
   );

-- Declarations

END aes_mix_columns ;

--
-- VHDL Architecture zybo_aes_hdl_lib.aes_mix_columns.struct
--
-- Created:
--          by - Shahin.UNKNOWN (DESKTOP-THSND8B)
--          at - 15:23:04 05/27/2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY zybo_aes_hdl_lib;

ARCHITECTURE struct OF aes_mix_columns IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL b0     : std_logic_vector(7 DOWNTO 0);
   SIGNAL b1     : std_logic_vector(7 DOWNTO 0);
   SIGNAL b10    : std_logic_vector(7 DOWNTO 0);
   SIGNAL b11    : std_logic_vector(7 DOWNTO 0);
   SIGNAL b12    : std_logic_vector(7 DOWNTO 0);
   SIGNAL b13    : std_logic_vector(7 DOWNTO 0);
   SIGNAL b14    : std_logic_vector(7 DOWNTO 0);
   SIGNAL b15    : std_logic_vector(7 DOWNTO 0);
   SIGNAL b2     : std_logic_vector(7 DOWNTO 0);
   SIGNAL b3     : std_logic_vector(7 DOWNTO 0);
   SIGNAL b4     : std_logic_vector(7 DOWNTO 0);
   SIGNAL b5     : std_logic_vector(7 DOWNTO 0);
   SIGNAL b6     : std_logic_vector(7 DOWNTO 0);
   SIGNAL b7     : std_logic_vector(7 DOWNTO 0);
   SIGNAL b8     : std_logic_vector(7 DOWNTO 0);
   SIGNAL b9     : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout0  : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout1  : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout10 : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout11 : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout12 : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout13 : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout14 : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout15 : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout2  : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout3  : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout4  : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout5  : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout6  : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout7  : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout8  : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout9  : std_logic_vector(7 DOWNTO 0);


   -- ModuleWare signal declarations(v1.12) for instance 'U_4' of 'split'
   SIGNAL mw_U_4temp_din : std_logic_vector(127 DOWNTO 0);

   -- Component Declarations
   COMPONENT aes_mix_column
   PORT (
      mix_column_in_row_0  : IN     std_logic_vector (7 DOWNTO 0);
      mix_column_in_row_1  : IN     std_logic_vector (7 DOWNTO 0);
      mix_column_in_row_2  : IN     std_logic_vector (7 DOWNTO 0);
      mix_column_in_row_3  : IN     std_logic_vector (7 DOWNTO 0);
      mix_column_out_row_0 : OUT    std_logic_vector (7 DOWNTO 0);
      mix_column_out_row_1 : OUT    std_logic_vector (7 DOWNTO 0);
      mix_column_out_row_2 : OUT    std_logic_vector (7 DOWNTO 0);
      mix_column_out_row_3 : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : aes_mix_column USE ENTITY zybo_aes_hdl_lib.aes_mix_column;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_5' of 'merge'
   columns_mixed <= b15 & b14 & b13 & b12 & b11 & b10 & b9 & b8 & b7 & b6 & b5 & b4 & b3 & b2 & b1 & b0;

   -- ModuleWare code(v1.12) for instance 'U_4' of 'split'
   mw_U_4temp_din <= columns_in;
   u_4combo_proc: PROCESS (mw_U_4temp_din)
   VARIABLE temp_din: std_logic_vector(127 DOWNTO 0);
   BEGIN
      temp_din := mw_U_4temp_din(127 DOWNTO 0);
      dout0 <= temp_din(7 DOWNTO 0);
      dout1 <= temp_din(15 DOWNTO 8);
      dout2 <= temp_din(23 DOWNTO 16);
      dout3 <= temp_din(31 DOWNTO 24);
      dout4 <= temp_din(39 DOWNTO 32);
      dout5 <= temp_din(47 DOWNTO 40);
      dout6 <= temp_din(55 DOWNTO 48);
      dout7 <= temp_din(63 DOWNTO 56);
      dout8 <= temp_din(71 DOWNTO 64);
      dout9 <= temp_din(79 DOWNTO 72);
      dout10 <= temp_din(87 DOWNTO 80);
      dout11 <= temp_din(95 DOWNTO 88);
      dout12 <= temp_din(103 DOWNTO 96);
      dout13 <= temp_din(111 DOWNTO 104);
      dout14 <= temp_din(119 DOWNTO 112);
      dout15 <= temp_din(127 DOWNTO 120);
   END PROCESS u_4combo_proc;

   -- Instance port mappings.
   U_0 : aes_mix_column
      PORT MAP (
         mix_column_in_row_0  => dout11,
         mix_column_in_row_1  => dout10,
         mix_column_in_row_2  => dout9,
         mix_column_in_row_3  => dout8,
         mix_column_out_row_0 => b11,
         mix_column_out_row_1 => b10,
         mix_column_out_row_2 => b9,
         mix_column_out_row_3 => b8
      );
   U_1 : aes_mix_column
      PORT MAP (
         mix_column_in_row_0  => dout15,
         mix_column_in_row_1  => dout14,
         mix_column_in_row_2  => dout13,
         mix_column_in_row_3  => dout12,
         mix_column_out_row_0 => b15,
         mix_column_out_row_1 => b14,
         mix_column_out_row_2 => b13,
         mix_column_out_row_3 => b12
      );
   U_2 : aes_mix_column
      PORT MAP (
         mix_column_in_row_0  => dout7,
         mix_column_in_row_1  => dout6,
         mix_column_in_row_2  => dout5,
         mix_column_in_row_3  => dout4,
         mix_column_out_row_0 => b7,
         mix_column_out_row_1 => b6,
         mix_column_out_row_2 => b5,
         mix_column_out_row_3 => b4
      );
   U_3 : aes_mix_column
      PORT MAP (
         mix_column_in_row_0  => dout3,
         mix_column_in_row_1  => dout2,
         mix_column_in_row_2  => dout1,
         mix_column_in_row_3  => dout0,
         mix_column_out_row_0 => b3,
         mix_column_out_row_1 => b2,
         mix_column_out_row_2 => b1,
         mix_column_out_row_3 => b0
      );

END struct;
