-- VHDL Entity zybo_aes_hdl_lib.aes_mul03.symbol
--
-- Created:
--          by - Shahin.UNKNOWN (DESKTOP-THSND8B)
--          at - 21:55:01 05/24/2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY aes_mul03 IS
   PORT( 
      mul_03_in  : IN     std_logic_vector (7 DOWNTO 0);
      mul_03_out : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END aes_mul03 ;

--
-- VHDL Architecture zybo_aes_hdl_lib.aes_mul03.struct
--
-- Created:
--          by - Shahin.UNKNOWN (DESKTOP-THSND8B)
--          at - 21:55:01 05/24/2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY zybo_aes_hdl_lib;

ARCHITECTURE struct OF aes_mul03 IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL mul_02_out : std_logic_vector(7 DOWNTO 0);


   -- Component Declarations
   COMPONENT aes_mul02
   PORT (
      mul_02_in  : IN     std_logic_vector (7 DOWNTO 0);
      mul_02_out : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : aes_mul02 USE ENTITY zybo_aes_hdl_lib.aes_mul02;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_1' of 'xor'
   mul_03_out <= mul_03_in XOR mul_02_out;

   -- Instance port mappings.
   U_0 : aes_mul02
      PORT MAP (
         mul_02_in  => mul_03_in,
         mul_02_out => mul_02_out
      );

END struct;
