-- VHDL Entity zybo_aes_hdl_lib.aes_ctr_block_128.symbol
--
-- Created:
--          by - Shahin.UNKNOWN (DESKTOP-THSND8B)
--          at - 11:25:52 06/16/2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY aes_ctr_block_128 IS
   PORT( 
      aes_ctr_start      : IN     std_logic;
      clk                : IN     std_logic;
      initial_counter_in : IN     std_logic_vector (31 DOWNTO 0);
      key_in             : IN     std_logic_vector (127 DOWNTO 0);
      m_axis_tready      : IN     std_logic;
      nonce_in           : IN     std_logic_vector (95 DOWNTO 0);
      reset_n            : IN     std_logic;
      s_axis_tdata       : IN     std_logic_vector (31 DOWNTO 0);
      s_axis_tkeep       : IN     std_logic_vector (3 DOWNTO 0);
      s_axis_tlast       : IN     std_logic;
      s_axis_tvalid      : IN     std_logic;
      aes_ctr_idle       : OUT    std_logic;
      m_axis_tdata       : OUT    std_logic_vector (31 DOWNTO 0);
      m_axis_tkeep       : OUT    std_logic_vector (3 DOWNTO 0);
      m_axis_tlast       : OUT    std_logic;
      m_axis_tvalid      : OUT    std_logic;
      s_axis_tready      : OUT    std_logic
   );

-- Declarations

END aes_ctr_block_128 ;

--
-- VHDL Architecture zybo_aes_hdl_lib.aes_ctr_block_128.struct
--
-- Created:
--          by - Shahin.UNKNOWN (DESKTOP-THSND8B)
--          at - 11:25:52 06/16/2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY zybo_aes_hdl_lib;

ARCHITECTURE struct OF aes_ctr_block_128 IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL aes_busy                 : std_logic;
   SIGNAL aes_done                 : std_logic;
   SIGNAL block_out                : std_logic_vector(127 DOWNTO 0);
   SIGNAL ciphertext_block         : std_logic_vector(127 DOWNTO 0);
   SIGNAL collector_done           : std_logic;
   SIGNAL counter_block_out        : std_logic_vector(127 DOWNTO 0);
   SIGNAL initialize_counter_block : std_logic;
   SIGNAL keep_block_out           : std_logic_vector(15 DOWNTO 0);
   SIGNAL keystream                : std_logic_vector(127 DOWNTO 0);
   SIGNAL last_word_mask_out       : std_logic_vector(3 DOWNTO 0);
   SIGNAL produce_counter_block    : std_logic;
   SIGNAL serializer_busy          : std_logic;
   SIGNAL serializer_done          : std_logic;
   SIGNAL serializer_last_done     : std_logic;
   SIGNAL start_aes                : std_logic;
   SIGNAL start_collector          : std_logic;
   SIGNAL start_serializer         : std_logic;

   -- Implicit buffer signal declarations
   SIGNAL s_axis_tready_internal : std_logic;


   -- Component Declarations
   COMPONENT aes_ctr_controller
   PORT (
      aes_busy                 : IN     std_logic ;
      aes_ctr_start            : IN     std_logic ;
      aes_done                 : IN     std_logic ;
      clk                      : IN     std_logic ;
      collector_busy           : IN     std_logic ;
      collector_done           : IN     std_logic ;
      reset_n                  : IN     std_logic ;
      serializer_busy          : IN     std_logic ;
      serializer_done          : IN     std_logic ;
      serializer_last_done     : IN     std_logic ;
      aes_ctr_idle             : OUT    std_logic ;
      initialize_counter_block : OUT    std_logic ;
      produce_counter_block    : OUT    std_logic ;
      start_aes                : OUT    std_logic ;
      start_collector          : OUT    std_logic ;
      start_serializer         : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT aes_ctr_counter_block
   PORT (
      clk                  : IN     std_logic ;
      initial_counter_in   : IN     std_logic_vector (31 DOWNTO 0);
      load_initial_counter : IN     std_logic ;
      next_block           : IN     std_logic ;
      nonce_in             : IN     std_logic_vector (95 DOWNTO 0);
      reset_n              : IN     std_logic ;
      counter_block_out    : OUT    std_logic_vector (127 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT aes_ctr_input_collector
   PORT (
      clk                      : IN     std_logic ;
      keep_in                  : IN     std_logic_vector (3 DOWNTO 0);
      last_in                  : IN     std_logic ;
      reset_n                  : IN     std_logic ;
      start_collector          : IN     std_logic ;
      word_in                  : IN     std_logic_vector (31 DOWNTO 0);
      word_valid               : IN     std_logic ;
      block_out                : OUT    std_logic_vector (127 DOWNTO 0);
      collector_done           : OUT    std_logic ;
      collector_ready_for_word : OUT    std_logic ;
      keep_block_out           : OUT    std_logic_vector (15 DOWNTO 0);
      last_word_mask_out       : OUT    std_logic_vector (3 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT aes_ctr_output_serializer
   PORT (
      ciphertext_block_in  : IN     std_logic_vector (127 DOWNTO 0);
      clk                  : IN     std_logic ;
      keep_block_in        : IN     std_logic_vector (15 DOWNTO 0);
      last_word_mask_in    : IN     std_logic_vector (3 DOWNTO 0);
      m_axis_tready        : IN     std_logic ;
      reset_n              : IN     std_logic ;
      start_serializer     : IN     std_logic ;
      m_axis_tdata         : OUT    std_logic_vector (31 DOWNTO 0);
      m_axis_tkeep         : OUT    std_logic_vector (3 DOWNTO 0);
      m_axis_tlast         : OUT    std_logic ;
      m_axis_tvalid        : OUT    std_logic ;
      serializer_busy      : OUT    std_logic ;
      serializer_done      : OUT    std_logic ;
      serializer_last_done : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT aes_encrypt_128
   PORT (
      aes_data_in  : IN     std_logic_vector (127 DOWNTO 0);
      aes_key_in   : IN     std_logic_vector (127 DOWNTO 0);
      aes_start    : IN     std_logic ;
      clk          : IN     std_logic ;
      reset_n      : IN     std_logic ;
      aes_busy     : OUT    std_logic ;
      aes_data_out : OUT    std_logic_vector (127 DOWNTO 0);
      aes_done     : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : aes_ctr_controller USE ENTITY zybo_aes_hdl_lib.aes_ctr_controller;
   FOR ALL : aes_ctr_counter_block USE ENTITY zybo_aes_hdl_lib.aes_ctr_counter_block;
   FOR ALL : aes_ctr_input_collector USE ENTITY zybo_aes_hdl_lib.aes_ctr_input_collector;
   FOR ALL : aes_ctr_output_serializer USE ENTITY zybo_aes_hdl_lib.aes_ctr_output_serializer;
   FOR ALL : aes_encrypt_128 USE ENTITY zybo_aes_hdl_lib.aes_encrypt_128;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_2' of 'xor'
   ciphertext_block <= keystream XOR block_out;

   -- Instance port mappings.
   U_5 : aes_ctr_controller
      PORT MAP (
         aes_busy                 => aes_busy,
         aes_ctr_start            => aes_ctr_start,
         aes_done                 => aes_done,
         clk                      => clk,
         collector_busy           => s_axis_tready_internal,
         collector_done           => collector_done,
         reset_n                  => reset_n,
         serializer_busy          => serializer_busy,
         serializer_done          => serializer_done,
         serializer_last_done     => serializer_last_done,
         aes_ctr_idle             => aes_ctr_idle,
         initialize_counter_block => initialize_counter_block,
         produce_counter_block    => produce_counter_block,
         start_aes                => start_aes,
         start_collector          => start_collector,
         start_serializer         => start_serializer
      );
   U_0 : aes_ctr_counter_block
      PORT MAP (
         clk                  => clk,
         initial_counter_in   => initial_counter_in,
         load_initial_counter => initialize_counter_block,
         next_block           => produce_counter_block,
         nonce_in             => nonce_in,
         reset_n              => reset_n,
         counter_block_out    => counter_block_out
      );
   U_3 : aes_ctr_input_collector
      PORT MAP (
         clk                      => clk,
         keep_in                  => s_axis_tkeep,
         last_in                  => s_axis_tlast,
         reset_n                  => reset_n,
         start_collector          => start_collector,
         word_in                  => s_axis_tdata,
         word_valid               => s_axis_tvalid,
         block_out                => block_out,
         collector_done           => collector_done,
         collector_ready_for_word => s_axis_tready_internal,
         keep_block_out           => keep_block_out,
         last_word_mask_out       => last_word_mask_out
      );
   U_4 : aes_ctr_output_serializer
      PORT MAP (
         ciphertext_block_in  => ciphertext_block,
         clk                  => clk,
         keep_block_in        => keep_block_out,
         last_word_mask_in    => last_word_mask_out,
         m_axis_tready        => m_axis_tready,
         reset_n              => reset_n,
         start_serializer     => start_serializer,
         m_axis_tdata         => m_axis_tdata,
         m_axis_tkeep         => m_axis_tkeep,
         m_axis_tlast         => m_axis_tlast,
         m_axis_tvalid        => m_axis_tvalid,
         serializer_busy      => serializer_busy,
         serializer_done      => serializer_done,
         serializer_last_done => serializer_last_done
      );
   U_1 : aes_encrypt_128
      PORT MAP (
         aes_data_in  => counter_block_out,
         aes_key_in   => key_in,
         aes_start    => start_aes,
         clk          => clk,
         reset_n      => reset_n,
         aes_busy     => aes_busy,
         aes_data_out => keystream,
         aes_done     => aes_done
      );

   -- Implicit buffered output assignments
   s_axis_tready <= s_axis_tready_internal;

END struct;
