-- VHDL Entity zybo_aes_hdl_lib.aes_mul02.symbol
--
-- Created:
--          by - Shahin.UNKNOWN (DESKTOP-THSND8B)
--          at - 21:54:04 05/24/2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY aes_mul02 IS
   PORT( 
      mul_02_in  : IN     std_logic_vector (7 DOWNTO 0);
      mul_02_out : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END aes_mul02 ;

--
-- VHDL Architecture zybo_aes_hdl_lib.aes_mul02.struct
--
-- Created:
--          by - Shahin.UNKNOWN (DESKTOP-THSND8B)
--          at - 21:54:04 05/24/2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF aes_mul02 IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL bit_0              : std_logic;
   SIGNAL bit_1              : std_logic;
   SIGNAL bit_2              : std_logic;
   SIGNAL bit_3              : std_logic;
   SIGNAL bit_4              : std_logic;
   SIGNAL bit_5              : std_logic;
   SIGNAL bit_6              : std_logic;
   SIGNAL bit_7              : std_logic;
   SIGNAL reduced_byte       : std_logic_vector(7 DOWNTO 0);
   SIGNAL reduction_constant : std_logic_vector(7 DOWNTO 0);
   SIGNAL shifted_byte       : std_logic_vector(7 DOWNTO 0);
   SIGNAL zero_bit           : std_logic;


   -- ModuleWare signal declarations(v1.12) for instance 'U_0' of 'split'
   SIGNAL mw_U_0temp_din : std_logic_vector(7 DOWNTO 0);


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_2' of 'constval'
   reduction_constant <= x"1B";

   -- ModuleWare code(v1.12) for instance 'U_5' of 'constval'
   zero_bit <= '0';

   -- ModuleWare code(v1.12) for instance 'U_1' of 'merge'
   shifted_byte <= bit_6 & bit_5 & bit_4 & bit_3 & bit_2 & bit_1 & bit_0 & zero_bit;

   -- ModuleWare code(v1.12) for instance 'U_3' of 'mux'
   u_3combo_proc: PROCESS(shifted_byte, reduced_byte, bit_7)
   BEGIN
      CASE bit_7 IS
      WHEN '0' => mul_02_out <= shifted_byte;
      WHEN '1' => mul_02_out <= reduced_byte;
      WHEN OTHERS => mul_02_out <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_3combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_0' of 'split'
   mw_U_0temp_din <= mul_02_in;
   u_0combo_proc: PROCESS (mw_U_0temp_din)
   VARIABLE temp_din: std_logic_vector(7 DOWNTO 0);
   BEGIN
      temp_din := mw_U_0temp_din(7 DOWNTO 0);
      bit_0 <= temp_din(0);
      bit_1 <= temp_din(1);
      bit_2 <= temp_din(2);
      bit_3 <= temp_din(3);
      bit_4 <= temp_din(4);
      bit_5 <= temp_din(5);
      bit_6 <= temp_din(6);
      bit_7 <= temp_din(7);
   END PROCESS u_0combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_4' of 'xor'
   reduced_byte <= shifted_byte XOR reduction_constant;

   -- Instance port mappings.

END struct;
